config/routes.rb
Rails.application.routes.draw do
  root 'application#welcome'
  get '/home', to: 'application#home'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'
  get '/auth/:provider/callback', to: 'sessions#omniauth'
  resources :recommendations
  resources :users do 
    resources :recommendations, only: [:index, :new, :create]
  end
  resources :media_assets do
    resources :recommendations, only:[:index]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/media.rb
class Media < ApplicationRecord
    has_many :recommendations
    has_many :users, through: :recommendations

    validates :title, presence: true 

    def self.search(query) 
        self.where("title LIKE ?", "%#{query}%")
    end
end

app/models/media_asset.rb
class MediaAsset < ApplicationRecord
    has_many :recommendations
    has_many :users, through: :recommendations

    validates :title, presence: true 
    validates :title, uniqueness: {case_sensitive: false}


    def self.search(query) 
        self.where("title LIKE ?", "%#{query}%")
    end
end

app/models/recommendation.rb
class Recommendation < ApplicationRecord
    belongs_to :recommendation_maker, class_name: "User"
    belongs_to :recommendation_receiver, class_name: "User"
    belongs_to :media_asset  
    accepts_nested_attributes_for :media_asset, reject_if: :all_blank 

    validates :rating, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 10 }


    def self.most_recent
      self.order(created_at: :desc).includes(:media_asset, :recommendation_maker, :recommendation_receiver)
    end

    
end

app/models/tv_movie.rb
class TvMovie < ApplicationRecord
    has_many :recommendations
    has_many :users, through: :recommendations

    validates :title, presence: true 

    def self.search(query) 
        self.where("title LIKE ?", "%#{query}%")
    end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :received_recommendations, class_name: "Recommendation", foreign_key: "recommendation_receiver_id", dependent: :destroy
  has_many :made_recommendations, class_name: "Recommendation", foreign_key: "recommendation_maker_id", dependent: :destroy
  has_many :media_assets, through: :recommendations

  validates :username, :email, presence: true
  validates :username, :email, uniqueness: {case_sensitive: false}
 
  def self.search(query) 
    self.where("username LIKE ?", "%#{query}%")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include ApplicationHelper
    before_action :authenticate_user, except: [:welcome]

    def welcome 
        if logged_in?
            redirect_to home_path
        end
    end

    def home 
        @recommendations = Recommendation.most_recent 
    end

    private 
    
    def authenticate_user 
        if !logged_in?
            redirect_to root_path
        end
    end
end

app/controllers/media_assets_controller.rb
class MediaAssetsController < ApplicationController
    before_action :set_media_asset, except: [:index, :create, :new]
    
    def index
        if params[:query] 
            @media_assets = MediaAsset.search(params[:query])
          else
            @media_assets = MediaAsset.all
        end
    end
    
    def new
        @media_asset = MediaAsset.new 
    end
    
    def create
        @media_asset = MediaAsset.new(media_asset_params)
        if @media_asset.save
            redirect_to media_asset_path(@media_asset)
        else
            render :new 
        end
    end
    
    def show
    end

    def edit
    end

    def update
        if @media_asset.update(media_asset_params)
            redirect_to media_asset_path(@media_asset) 
        else
            render :edit 
        end
    end

    
    private
    
    def media_asset_params 
        params.require(:media_asset).permit(:title, :media_type)
    end

    def set_media_asset
        @media_asset = MediaAsset.find_by_id(params[:id])
    end
end

app/controllers/recommendations_controller.rb
class RecommendationsController < ApplicationController
    before_action :set_recommendation_receiver, except: [:destroy]
    
    def index
        if params[:user_id]
            @recommendations = @user.received_recommendations
        else
            @recommendations = current_user.made_recommendations
        end
        if params[:media_asset_id]
           @media_asset = MediaAsset.find_by_id(params[:media_asset_id])
            @recommendations = @media_asset.recommendations 
        end
    end

    def new
        if params[:user_id]
            @recommendation = @user.received_recommendations.build 
        else
            redirect_to user_path(current_user)
        end
    end

    def create
        if params[:user_id]
            @recommendation = Recommendation.new(recommendation_params)
            @recommendation.recommendation_receiver = @user 
            @recommendation.recommendation_maker = current_user
            if @recommendation.save 
                redirect_to user_path(@user)
            else
                render :new 
            end
        else
            redirect_to user_path(current_user)        
        end
    end

    def destroy
        @recommendation = Recommendation.find_by_id(params[:id]) 
        @recommendation.destroy 
        redirect_to user_path(current_user)
    end


    private

    def recommendation_params
        params.require(:recommendation).permit(:rating, :recommendation_maker_id, :recommendation_receiver_id, :media_asset_id, media_asset_attributes:[:title, :media_type])
    end

    def set_recommendation_receiver
        @user = User.find_by_id(params[:user_id])
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate_user, except: [:destroy]
  
  def new
    if logged_in?
      redirect_to home_path
    end
  end

  def create
    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id 
      redirect_to home_path
    else
      render :new 
    end
  end

  def destroy
    session.delete :user_id 
    redirect_to root_path 
  end

  def omniauth 
    user = User.find_or_create_by(uid: auth[:uid], provider: auth[:provider]) do |u|
      u.username = auth[:info][:name]
      u.email = auth[:info][:email]
      u.password = SecureRandom.hex(15)
    end
    if user.valid?
      session[:user_id] = user.id 
      redirect_to home_path
    else
      redirect_to login_path 
    end
  end
  private
  def auth 
    request.env['omniauth.auth']
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, except: [:index, :new, :create]
    skip_before_action :authenticate_user, only: [:new, :create]
    
    def index
        if params[:query] 
            @users = User.search(params[:query])
          else
            @users = User.all
        end
    end

    def new 
        if logged_in?
            redirect_to home_path
        else
            @user = User.new
        end
    end

    def create 
        @user = User.new(user_params)
        if @user.save 
            session[:user_id] = @user.id 
            redirect_to home_path
        else
            render :new 
        end
    end

    def show
    end

    def edit 
    end

    def update
        if @user.update(user_params)
            redirect_to user_path(@user)
        else
            render :edit 
        end
    end

    def destroy
        @user.destroy 
        redirect_to root_path
    end

    private

    def user_params
        params.require(:user).permit(:username, :email, :password)
    end

    def set_user
        @user = User.find_by_id(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def current_user
        @current_user ||= User.find_by_id(session[:user_id])
    end

    def logged_in?
        current_user
    end

    def check_user?
        current_user == User.find_by_id(params[:id])
    end
end

app/helpers/media_assets_helper.rb
module MediaAssetsHelper
end

app/helpers/recommendations_helper.rb
module RecommendationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/home.html.erb
<div class="container">
<h1>Most Recent Recommendations</h1>
<hr>
<ul>
<% @recommendations.each do |recommendation| %>
   <li> <%= render partial: 'recommendations/media', locals: {recommendation: recommendation}  %> 
    was recommended to <%= render partial: 'recommendations/receiver', locals: {recommendation: recommendation} %>
    by <%= render partial: 'recommendations/maker', locals: {recommendation: recommendation}  %> </li>
    <hr>
<% end %>
</ul>
</div>

app/views/application/welcome.html.erb
<br>
<div class="container">
<h1>Welcome to Queue!</h1>
<h3>Queue is a recommendation platform where users can connect and share TV shows and Movies to watch.</h3>
<br>
<h4>Create an account and start adding TV shows and Movies to users Queues!</h4>


<%= link_to "Sign Up", new_user_path, :class => "link" %> | <%= link_to "Login", login_path, :class => "link" %>

<br>
<br>
<h4>Sign In With Google</h4>
<%= button_to 'Google Sign In', '/auth/google_oauth2', :class => 'btn btn-light' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Queue</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if current_user %>
  <nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href=<%= home_path %>>Home</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href=<%= users_path %>>Search Users</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href=<%= media_assets_path %>>Search Movies and TV</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href=<%= user_path(current_user) %>>Profile Page</a>
        </li>
        <li class="nav-item">
        <a class="nav-link" href=<%= recommendations_path %>>Recommendations Made</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

  <% end %>
    <%= yield %>
  </body>
</html>

app/views/media_assets/_form.html.erb
<%= form_with model: @media_asset do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>

    <%= f.label :media_type %>
    <%= f.select :media_type, ["Movie", "Tv Show"], include_blank: true  %>

    <%= f.submit :Submit, class: 'btn btn-light' %>
<% end %>

app/views/media_assets/edit.html.erb
<div class="container">
<h2>Edit A Movie Or Tv Show</h2>
<hr>
<%= render partial: 'users/errors', locals: {model: @media_asset} %>

<%= render partial: 'form' %>
</div>

app/views/media_assets/index.html.erb
<div class="container">
<h2>Search For Movies and Tv Shows</h2>
<hr>
<%= form_with model: @media_asset, method: :get do |f| %>
    <%= f.text_field :query %>
    <%= f.submit :Search, class: 'btn btn-light' %>
<% end %>


<p><%= link_to "Create A New Movie Or Tv Show", new_media_asset_path, :class => "link" %></p>



<ul>
<% @media_assets.each do |media_asset| %>
   <li><%= link_to media_asset.title, media_asset_path(media_asset), :class => "link" %> - <%= media_asset.media_type %></li>
<% end %>
</ul>
</div>

app/views/media_assets/new.html.erb
<div class="container">
<h2>Create A New Movie Or Tv Show</h2>
<hr>
<%= render partial: 'users/errors', locals: {model: @media_asset} %>

<%= render partial: 'form' %>
</div>

app/views/media_assets/show.html.erb
<div class="container">
<h2><%= @media_asset.title %></h2>

<h3><%= @media_asset.media_type %></h3>


<p><%=link_to "Edit", edit_media_asset_path(@media_asset), :class => "link" %></p>

<p><%=link_to "All Movies and TV Shows", media_assets_path, :class => "link" %></p>
</div>

app/views/medias/new.html.erb
<p>Create A New Movie Or Tv Show</p>
<%= form_with model: @media do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>

    <%= f.label :media_type %>
    <%= f.select :media_type, ["Movie", "Tv Show"] %>

    <%= f.submit %>
<% end %>

app/views/medias/show.html.erb
<p><%= @media.title %></p>

<p><%= @media.media_type %></p>

<p><%= button_to "Add To User Recommendations", recommendations_path %></p>

<p><%=link_to "All Movies and TV Shows", medias_path %></p>




# <%= form_with model: @recommendation do |f| %>
#     <%= f.submit "Add To User Recommendation" %>
# <% end %>

app/views/recommendations/_maker.html.erb
<%= link_to recommendation.recommendation_maker.username, user_path(recommendation.recommendation_maker), :class => "link" %>

app/views/recommendations/_media.html.erb
<%= link_to recommendation.media_asset.title, media_asset_path(recommendation.media_asset), :class => "link" %> 

app/views/recommendations/_receiver.html.erb
<%= link_to recommendation.recommendation_receiver.username, user_path(recommendation.recommendation_receiver), :class => "link" %>

app/views/recommendations/_recommendation_maker.html.erb
<%= link_to recommendation.recommendation_maker.username, user_path(recommendation.recommendation_maker) %>

app/views/recommendations/_recommendation_media.html.erb
<%= link_to recommendation.media_asset.title, media_asset_path(recommendation.media_asset) %> 

app/views/recommendations/_recommendation_receiver.html.erb
<%= link_to recommendation.recommendation_receiver.username, user_path(recommendation.recommendation_receiver) %>

app/views/recommendations/index.html.erb
<div class="container">
<h2>Recommendations</h2>
<hr>
<ul>
<% @recommendations.each do |recommendation| %>
   <li> <%= render partial: 'recommendations/media', locals: {recommendation: recommendation}  %> - <%= render partial: 'recommendations/receiver', locals: {recommendation: recommendation}  %> </li>
<% end %>
</ul>
</div>

app/views/recommendations/new.html.erb
<div class="container">
<h2>Make A Recommendation</h2>
<hr>
<%= render partial: 'users/errors', locals: {model: @recommendation} %>


<%= form_with model: [@user, @recommendation] do |f| %>
    <p>Select A Movie Or TV Show</p>
    <%= f.collection_select :media_asset_id, MediaAsset.all, :id, :title, include_blank: true %>

    <br>
    <p>Create A New Movie Or TV Show</p>
    <%= f.fields_for :media_asset, @recommendation.build_media_asset do |media_asset_fields| %>
      <%= media_asset_fields.text_field :title %>
      <%= media_asset_fields.select :media_type, ["Movie", "Tv Show"], include_blank: true %>
    <% end %>
    
    <br>
    <p>Rate Your Recommendation</p>
    <%= f.label :rating %>
    <%= f.number_field :rating %>
    
    <%= f.submit :Submit, class: 'btn btn-light' %>
<% end %>
</div>

app/views/tv_movies/show.html.erb
<p><%= @tv_movie.title %></p>

<p><%= @tv_movie.content_type %></p>

<p><%= button_to "Add To User Recommendations", recommendations_path %></p>

<p><%=link_to "All Movies and TV Shows", tv_movies_path %></p>




# <%= form_with model: @recommendation do |f| %>
#     <%= f.submit "Add To User Recommendation" %>
# <% end %>

app/views/users/_errors.html.erb
<% if model.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(model.errors.count, "error") %> occured:</h2>

  <ul>
    <% model.errors.each do |error| %>
      <li><%= error.full_message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/users/_form.html.erb
<%= form_with model: @user do |f| %>
    <%=f.label :username %>
    <%=f.text_field :username %> <br>

    <%=f.label :email %>
    <%=f.email_field :email %> <br>

    <%=f.label :password %>
    <%=f.password_field :password %> <br>

    <%=f.submit :Create, class: 'btn btn-light' %> 
<% end %>

app/views/users/edit.html.erb
<div class="container">
<h3>Edit Account</h3> 

<%= render partial: 'errors', locals: {model: @user} %>

<%= render partial: 'form' %>

<%= button_to "delete account", @user, :method => :delete, :class => 'btn btn-light' %>
</div>

app/views/users/index.html.erb
<div class="container">
<h2>Search For Users</h2>
<hr>
<%= form_with url: users_path, method: :get do |f| %>
    <%= f.text_field :query %>
    <%= f.submit :Search, class: 'btn btn-light' %>
<% end %>

<ul>
<% @users.each do |user| %>
   <li><%= link_to user.username, user_path(user), :class => "link" %></li>
<% end %>
</ul>
</div>

app/views/users/new.html.erb
<br>
<div class="container">
<h3>Sign Up</h3> 

<%= render partial: 'errors', locals: {model: @user} %>

<%= render partial: 'form' %>


<h3>Sign In With Google</h3>

<%= button_to 'Google Sign In', '/auth/google_oauth2', :class => 'btn btn-light' %>
</div>

app/views/users/show.html.erb
<br>

<div class="container">
<h2><%= @user.username %>'s Profile Page</h2>
<hr>
<% if !check_user? %>
    <p><%= link_to "Make a recommendation", new_user_recommendation_path(@user), :class => "link" %></p>
<% end %>


<h3>Recommendations</h3>
<hr>
<% @user.received_recommendations.each do |recommendation| %>
   <p> <%= render partial: 'recommendations/media', locals: {recommendation: recommendation} %> - Rating: <%= recommendation.rating %> </p>
   <p> Recommended By: <%= render partial: 'recommendations/maker', locals: {recommendation: recommendation}  %> </p>
   <% if check_user? %>
        <%= button_to "delete", recommendation, :method => :delete, :class => 'btn btn-light' %>
   <% end %>
    <hr>
<% end %>



<% if check_user? %>
    <p><%=link_to "Edit Account", edit_user_path(@user), :class => "link" %></p>
    <p><%=button_to "Logout", '/logout', :class => 'btn btn-light' %></p>
<% end %>
</div>